version: "3.8"

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    restart: always
    environment:
      - MH_STORAGE=maildir # memory / mongodb / maildir
      - MH_MAILDIR_PATH=/mail-volume
    volumes:
      - mailhog-volume:/mail-volume
volumes:
  mailhog-volume:

