version: "3.8"

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    restart: on-failure
    environment:
      - MH_STORAGE=maildir # memory || mongodb || maildir

