version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:v1.0.1
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant-volume:/qdrant/storage

volumes:
  qdrant-volume:
